# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/preprocessor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/preprocessor.proto\x12\x0cpreprocessor\"b\n\x13PreprocessorRequest\x12\x0f\n\x07rawText\x18\x01 \x01(\t\x12:\n\x11processingOptions\x18\x02 \x01(\x0b\x32\x1f.preprocessor.ProcessingOptions\"\x8d\x01\n\x11ProcessingOptions\x12\x17\n\x0fremoveStopWords\x18\x01 \x01(\x08\x12\x10\n\x08stemming\x18\x02 \x01(\x08\x12\x11\n\tfold_case\x18\x03 \x01(\x08\x12\x11\n\tnormalise\x18\x04 \x01(\x08\x12\x17\n\x0f\x65xpand_capitals\x18\x05 \x01(\x08\x12\x0e\n\x06ngrams\x18\x06 \x01(\x05\"b\n\x1bPreprocessorArticleResponse\x12\x18\n\x10preprocessedText\x18\x01 \x03(\t\x12\x11\n\ttextLinks\x18\x02 \x03(\t\x12\x16\n\x0etextCategories\x18\x03 \x03(\t\"4\n\x18PreprocessorTextResponse\x12\x18\n\x10preprocessedText\x18\x01 \x03(\t2\xdc\x01\n\x0cPreprocessor\x12h\n\x16preprocessorRawArticle\x12!.preprocessor.PreprocessorRequest\x1a).preprocessor.PreprocessorArticleResponse\"\x00\x12\x62\n\x13preprocessorRawText\x12!.preprocessor.PreprocessorRequest\x1a&.preprocessor.PreprocessorTextResponse\"\x00\x62\x06proto3')



_PREPROCESSORREQUEST = DESCRIPTOR.message_types_by_name['PreprocessorRequest']
_PROCESSINGOPTIONS = DESCRIPTOR.message_types_by_name['ProcessingOptions']
_PREPROCESSORARTICLERESPONSE = DESCRIPTOR.message_types_by_name['PreprocessorArticleResponse']
_PREPROCESSORTEXTRESPONSE = DESCRIPTOR.message_types_by_name['PreprocessorTextResponse']
PreprocessorRequest = _reflection.GeneratedProtocolMessageType('PreprocessorRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSORREQUEST,
  '__module__' : 'proto.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor.PreprocessorRequest)
  })
_sym_db.RegisterMessage(PreprocessorRequest)

ProcessingOptions = _reflection.GeneratedProtocolMessageType('ProcessingOptions', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSINGOPTIONS,
  '__module__' : 'proto.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor.ProcessingOptions)
  })
_sym_db.RegisterMessage(ProcessingOptions)

PreprocessorArticleResponse = _reflection.GeneratedProtocolMessageType('PreprocessorArticleResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSORARTICLERESPONSE,
  '__module__' : 'proto.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor.PreprocessorArticleResponse)
  })
_sym_db.RegisterMessage(PreprocessorArticleResponse)

PreprocessorTextResponse = _reflection.GeneratedProtocolMessageType('PreprocessorTextResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSORTEXTRESPONSE,
  '__module__' : 'proto.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:preprocessor.PreprocessorTextResponse)
  })
_sym_db.RegisterMessage(PreprocessorTextResponse)

_PREPROCESSOR = DESCRIPTOR.services_by_name['Preprocessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREPROCESSORREQUEST._serialized_start=42
  _PREPROCESSORREQUEST._serialized_end=140
  _PROCESSINGOPTIONS._serialized_start=143
  _PROCESSINGOPTIONS._serialized_end=284
  _PREPROCESSORARTICLERESPONSE._serialized_start=286
  _PREPROCESSORARTICLERESPONSE._serialized_end=384
  _PREPROCESSORTEXTRESPONSE._serialized_start=386
  _PREPROCESSORTEXTRESPONSE._serialized_end=438
  _PREPROCESSOR._serialized_start=441
  _PREPROCESSOR._serialized_end=661
# @@protoc_insertion_point(module_scope)
