# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data_controller.proto',
  package='data_controller',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x64\x61ta_controller.proto\x12\x0f\x64\x61ta_controller\"6\n\x0e\x41rticleRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x14\n\x0c\x61rticleTitle\x18\x02 \x01(\t\"C\n\x0b\x44umpRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x14\n\x0c\x61rticleTitle\x18\x02 \x01(\t\x12\x0e\n\x06\x64umpId\x18\x03 \x01(\x03\"2\n\x17LastUpdatedDateResponse\x12\x17\n\x0flastIndexedDate\x18\x01 \x01(\t\"#\n\x11\x43reateDumpRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\"\x18\n\x06\x44umpId\x12\x0e\n\x06\x64umpId\x18\x01 \x01(\x03\"\'\n\x14UpdateDumpIdResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\rPurgeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xe8\x01\n\x12IndexUpdateRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x17\n\x0flastUpdatedDate\x18\x03 \x01(\t\x12\x11\n\tnamespace\x18\x04 \x01(\t\x12\x0e\n\x06\x64umpId\x18\x05 \x01(\x03\x12\x15\n\rprocessedText\x18\x06 \x01(\t\x12\r\n\x05links\x18\x07 \x01(\t\x12\x12\n\ncategories\x18\x08 \x01(\t\x12\x11\n\ttemplates\x18\t \x01(\t\x12\x11\n\tabstracts\x18\n \x01(\t\x12\x17\n\x0f\x63itationsBodies\x18\x0b \x03(\t\"\x15\n\x13IndexUpdateResponse2\xc9\x03\n\x0e\x44\x61taController\x12\x65\n\x16getLastUpdatedDateTime\x12\x1f.data_controller.ArticleRequest\x1a(.data_controller.LastUpdatedDateResponse\"\x00\x12K\n\ncreateDump\x12\".data_controller.CreateDumpRequest\x1a\x17.data_controller.DumpId\"\x00\x12U\n\x0cupdateDumpId\x12\x1c.data_controller.DumpRequest\x1a%.data_controller.UpdateDumpIdResponse\"\x00\x12N\n\x11purgeThenComplete\x12\x17.data_controller.DumpId\x1a\x1e.data_controller.PurgeResponse\"\x00\x12\\\n\rupdateArticle\x12#.data_controller.IndexUpdateRequest\x1a$.data_controller.IndexUpdateResponse\"\x00\x62\x06proto3'
)




_ARTICLEREQUEST = _descriptor.Descriptor(
  name='ArticleRequest',
  full_name='data_controller.ArticleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='data_controller.ArticleRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='articleTitle', full_name='data_controller.ArticleRequest.articleTitle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=96,
)


_DUMPREQUEST = _descriptor.Descriptor(
  name='DumpRequest',
  full_name='data_controller.DumpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='data_controller.DumpRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='articleTitle', full_name='data_controller.DumpRequest.articleTitle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dumpId', full_name='data_controller.DumpRequest.dumpId', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=165,
)


_LASTUPDATEDDATERESPONSE = _descriptor.Descriptor(
  name='LastUpdatedDateResponse',
  full_name='data_controller.LastUpdatedDateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lastIndexedDate', full_name='data_controller.LastUpdatedDateResponse.lastIndexedDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=217,
)


_CREATEDUMPREQUEST = _descriptor.Descriptor(
  name='CreateDumpRequest',
  full_name='data_controller.CreateDumpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='data_controller.CreateDumpRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=254,
)


_DUMPID = _descriptor.Descriptor(
  name='DumpId',
  full_name='data_controller.DumpId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dumpId', full_name='data_controller.DumpId.dumpId', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=280,
)


_UPDATEDUMPIDRESPONSE = _descriptor.Descriptor(
  name='UpdateDumpIdResponse',
  full_name='data_controller.UpdateDumpIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='data_controller.UpdateDumpIdResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=321,
)


_PURGERESPONSE = _descriptor.Descriptor(
  name='PurgeResponse',
  full_name='data_controller.PurgeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='data_controller.PurgeResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=355,
)


_INDEXUPDATEREQUEST = _descriptor.Descriptor(
  name='IndexUpdateRequest',
  full_name='data_controller.IndexUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='data_controller.IndexUpdateRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='data_controller.IndexUpdateRequest.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastUpdatedDate', full_name='data_controller.IndexUpdateRequest.lastUpdatedDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='data_controller.IndexUpdateRequest.namespace', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dumpId', full_name='data_controller.IndexUpdateRequest.dumpId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='processedText', full_name='data_controller.IndexUpdateRequest.processedText', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='links', full_name='data_controller.IndexUpdateRequest.links', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categories', full_name='data_controller.IndexUpdateRequest.categories', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='templates', full_name='data_controller.IndexUpdateRequest.templates', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='abstracts', full_name='data_controller.IndexUpdateRequest.abstracts', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='citationsBodies', full_name='data_controller.IndexUpdateRequest.citationsBodies', index=10,
      number=11, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=590,
)


_INDEXUPDATERESPONSE = _descriptor.Descriptor(
  name='IndexUpdateResponse',
  full_name='data_controller.IndexUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=613,
)

DESCRIPTOR.message_types_by_name['ArticleRequest'] = _ARTICLEREQUEST
DESCRIPTOR.message_types_by_name['DumpRequest'] = _DUMPREQUEST
DESCRIPTOR.message_types_by_name['LastUpdatedDateResponse'] = _LASTUPDATEDDATERESPONSE
DESCRIPTOR.message_types_by_name['CreateDumpRequest'] = _CREATEDUMPREQUEST
DESCRIPTOR.message_types_by_name['DumpId'] = _DUMPID
DESCRIPTOR.message_types_by_name['UpdateDumpIdResponse'] = _UPDATEDUMPIDRESPONSE
DESCRIPTOR.message_types_by_name['PurgeResponse'] = _PURGERESPONSE
DESCRIPTOR.message_types_by_name['IndexUpdateRequest'] = _INDEXUPDATEREQUEST
DESCRIPTOR.message_types_by_name['IndexUpdateResponse'] = _INDEXUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArticleRequest = _reflection.GeneratedProtocolMessageType('ArticleRequest', (_message.Message,), {
  'DESCRIPTOR' : _ARTICLEREQUEST,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.ArticleRequest)
  })
_sym_db.RegisterMessage(ArticleRequest)

DumpRequest = _reflection.GeneratedProtocolMessageType('DumpRequest', (_message.Message,), {
  'DESCRIPTOR' : _DUMPREQUEST,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.DumpRequest)
  })
_sym_db.RegisterMessage(DumpRequest)

LastUpdatedDateResponse = _reflection.GeneratedProtocolMessageType('LastUpdatedDateResponse', (_message.Message,), {
  'DESCRIPTOR' : _LASTUPDATEDDATERESPONSE,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.LastUpdatedDateResponse)
  })
_sym_db.RegisterMessage(LastUpdatedDateResponse)

CreateDumpRequest = _reflection.GeneratedProtocolMessageType('CreateDumpRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDUMPREQUEST,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.CreateDumpRequest)
  })
_sym_db.RegisterMessage(CreateDumpRequest)

DumpId = _reflection.GeneratedProtocolMessageType('DumpId', (_message.Message,), {
  'DESCRIPTOR' : _DUMPID,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.DumpId)
  })
_sym_db.RegisterMessage(DumpId)

UpdateDumpIdResponse = _reflection.GeneratedProtocolMessageType('UpdateDumpIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEDUMPIDRESPONSE,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.UpdateDumpIdResponse)
  })
_sym_db.RegisterMessage(UpdateDumpIdResponse)

PurgeResponse = _reflection.GeneratedProtocolMessageType('PurgeResponse', (_message.Message,), {
  'DESCRIPTOR' : _PURGERESPONSE,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.PurgeResponse)
  })
_sym_db.RegisterMessage(PurgeResponse)

IndexUpdateRequest = _reflection.GeneratedProtocolMessageType('IndexUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _INDEXUPDATEREQUEST,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.IndexUpdateRequest)
  })
_sym_db.RegisterMessage(IndexUpdateRequest)

IndexUpdateResponse = _reflection.GeneratedProtocolMessageType('IndexUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _INDEXUPDATERESPONSE,
  '__module__' : 'data_controller_pb2'
  # @@protoc_insertion_point(class_scope:data_controller.IndexUpdateResponse)
  })
_sym_db.RegisterMessage(IndexUpdateResponse)



_DATACONTROLLER = _descriptor.ServiceDescriptor(
  name='DataController',
  full_name='data_controller.DataController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=616,
  serialized_end=1073,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLastUpdatedDateTime',
    full_name='data_controller.DataController.getLastUpdatedDateTime',
    index=0,
    containing_service=None,
    input_type=_ARTICLEREQUEST,
    output_type=_LASTUPDATEDDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='createDump',
    full_name='data_controller.DataController.createDump',
    index=1,
    containing_service=None,
    input_type=_CREATEDUMPREQUEST,
    output_type=_DUMPID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateDumpId',
    full_name='data_controller.DataController.updateDumpId',
    index=2,
    containing_service=None,
    input_type=_DUMPREQUEST,
    output_type=_UPDATEDUMPIDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='purgeThenComplete',
    full_name='data_controller.DataController.purgeThenComplete',
    index=3,
    containing_service=None,
    input_type=_DUMPID,
    output_type=_PURGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateArticle',
    full_name='data_controller.DataController.updateArticle',
    index=4,
    containing_service=None,
    input_type=_INDEXUPDATEREQUEST,
    output_type=_INDEXUPDATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATACONTROLLER)

DESCRIPTOR.services_by_name['DataController'] = _DATACONTROLLER

# @@protoc_insertion_point(module_scope)
