# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ingress_controller_pb2 as ingress__controller__pb2


class IngressControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.updateIndex = channel.unary_unary(
                '/ingress_controller.IngressController/updateIndex',
                request_serializer=ingress__controller__pb2.UpdateIndexRequest.SerializeToString,
                response_deserializer=ingress__controller__pb2.UpdateIndexReply.FromString,
                )


class IngressControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def updateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngressControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'updateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.updateIndex,
                    request_deserializer=ingress__controller__pb2.UpdateIndexRequest.FromString,
                    response_serializer=ingress__controller__pb2.UpdateIndexReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ingress_controller.IngressController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IngressController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def updateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ingress_controller.IngressController/updateIndex',
            ingress__controller__pb2.UpdateIndexRequest.SerializeToString,
            ingress__controller__pb2.UpdateIndexReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
