# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import preprocessor_pb2 as preprocessor__pb2


class PreprocessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.preprocessText = channel.unary_unary(
                '/preprocessor.Preprocessor/preprocessText',
                request_serializer=preprocessor__pb2.PreprocessorRequest.SerializeToString,
                response_deserializer=preprocessor__pb2.PreprocessorTextResponse.FromString,
                )


class PreprocessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def preprocessText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreprocessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'preprocessText': grpc.unary_unary_rpc_method_handler(
                    servicer.preprocessText,
                    request_deserializer=preprocessor__pb2.PreprocessorRequest.FromString,
                    response_serializer=preprocessor__pb2.PreprocessorTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'preprocessor.Preprocessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Preprocessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def preprocessText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/preprocessor.Preprocessor/preprocessText',
            preprocessor__pb2.PreprocessorRequest.SerializeToString,
            preprocessor__pb2.PreprocessorTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
