# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wiki_search_pb2 as wiki__search__pb2


class WikiSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.updateIndex = channel.unary_unary(
                '/wiki_search.WikiSearch/updateIndex',
                request_serializer=wiki__search__pb2.CheckIndexRequest.SerializeToString,
                response_deserializer=wiki__search__pb2.CheckIndexReply.FromString,
                )


class WikiSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def updateIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WikiSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'updateIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.updateIndex,
                    request_deserializer=wiki__search__pb2.CheckIndexRequest.FromString,
                    response_serializer=wiki__search__pb2.CheckIndexReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wiki_search.WikiSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WikiSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def updateIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wiki_search.WikiSearch/updateIndex',
            wiki__search__pb2.CheckIndexRequest.SerializeToString,
            wiki__search__pb2.CheckIndexReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
